### ISSUE TITLE
Whitespace doesn't get removed for .slim files

### ISSUE THREAD

**Issue by danielcgold** [atom/whitespace#123]
I have several slim files and whitespace doesn't get removed upon saving.

**Comment by dakotahp** [comment]
➕1️⃣ I have this issue as well as everyone else in my company. Our slim templates are filled with random whitespace. Is there any config settings to force this in the meantime? The following does _not_ work:

```cson
".slim":
  whitespace:
    removeTrailingWhitespace: true
```

**Comment by codebryo** [comment]
If that is not working for some one, I had it working for me using:
```
".slim.text":
  editor:
    preferredLineLength: 120
    softWrapHangingIndent: 2
  whitespace:
    ignoreWhitespaceOnCurrentLine: false
    ignoreWhitespaceOnlyLines: false
    removeTrailingWhitespace: true
```

and be sure  to have it added to the end of the config file. It didn't work for me when it was somewhere in between.
