### ISSUE TITLE
Whitespace stripped from markdown despite settings

### ISSUE THREAD

**Issue by amygroshek** [atom/whitespace#167]
### Prerequisites

* [x ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Whitespace is being stripped from .md files despite the plugin "Keep markdown line break whitespace" option being selected. I also tried to override by blacklisting .md files in config.cson, to no effect:

```
  whitespace:
    fileBlacklist: [
      "*.md"
    ]
    scopeBlacklist: [
      ".source.gfm"
    ]
```
And tried in various ways to set the setting in config.cson:

```
"*":
  "":
    gfm:
      source:
        whitespace:
          removeTrailingWhitespace: false
    source:
      gfm:
        editor:
          removeTrailingWhitespace: false
    text:
      md:
        whitespace:
          removeTrailingWhitespace: false
```

### Steps to Reproduce

1. Install plugin/verify that plugin is enabled
2. In plugin settings, make sure that the "Keep Markdown Line Break Whitespace" option is checked
3. Open an .md file and add two-space line breaks to some lines
4. Save the file

**Expected behavior:** Whitespace is not removed

**Actual behavior:** Whitespace is removed

**Reproduces how often:** Every time I save a file

### Versions

macpro@~ $: atom --version
Atom    : 1.22.1
Electron: 1.6.15
Chrome  : 56.0.2924.87
Node    : 7.4.0
macpro@~ $: apm --version
apm  1.18.8
npm  3.10.10
node 6.9.5 x64
python 2.7.10
git 2.5.4

### Additional Information

Sorry, I know there are a lot of markdown issues in this repo, but this is driving me nuts. Screenshot shows my settings and the two file format blacklist settings reflected from the config file.

![screen shot 2017-11-16 at 11 49 37 am](https://user-images.githubusercontent.com/746182/32907359-5db89274-cac5-11e7-9bed-97db25fd3af9.png)
