### ISSUE TITLE
syntax-scope configs broken (again)

### ISSUE THREAD

**Issue by SampsonCrowley** [atom/whitespace#172]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    `Checked that your issue isn't already filed: (**you asked me to open a new one**)`
    
### Description

exactly as the title states. syntax-scope configs don't work

### Steps to Reproduce
add syntax-scope configs to a "text.html.ruby" file

#### MY setup
result of scope Descriptor:
```
scopes:
  0: "text.html.ruby"
  1: "source.ruby.rails.embedded.html"
  2: "string.quoted.single.ruby"
  3: "punctuation.definition.string.begin.ruby"
```
relevant config.cson
```
"text.html.ruby":
  whitespace:
    ensureSingleTrailingNewline: false
    removeTrailingWhitespace: false
"text.plain":
  whitespace:
    ensureSingleTrailingNewline: false
    removeTrailingWhitespace: false
```

**Expected behavior:**
trailing newlines aren't added for text.html.ruby files

**Actual behavior:**
As you can see, `text.html.ruby` is clearly a scope of the file i am using, yet setting ensureSingleTrailingNewline: false does absolutely nothing. Whitespace keeps adding the newline anyways

**Reproduces how often:**
100% (two separate computers on 2 separate Atom versions, `< 1.23.1` && `1.23.1`)

### Versions
Atom    : 1.23.1
Electron: 1.6.15
Chrome  : 56.0.2924.87
Node    : 7.4.0

apm  1.18.12
npm  5.6.0
node 9.3.0 x64
atom 1.23.1
python 2.7.14
git 2.15.1

### Additional Information

You already prematurely closed an existing issues with this same problem.

Disabled this package until fixed, as I'd rather have no STN than for this package to ignore my settings
